{
 "title": "story",
 "description": "A dashboard for story node",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "jobs", "query": { "query": "label_values(job)" } },
   { "name": "chain", "query": "${VAR_CHAIN}" },
   { "name": "node", "query": "${VAR_NODE}" },
   {
    "name": "instance",
    "query": {
     "query": "label_values(up{job=~\"$jobs\",label=\"$node\"}, instance)"
    }
   },
   { "name": "quantile", "label": "quantile", "query": "${VAR_QUANTILE}" }
  ]
 },
 "panels": [
  { "title": "Consensus Client Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Node consensus height",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "cometbft_consensus_height{label=\"$node\"}",
     "legendFormat": "cometbft consensus height"
    }
   ]
  },
  {
   "title": "Sync Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_blocksync_syncing{label=\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Peers",
   "type": "gauge",
   "description": "cometbft connected peers",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_p2p_peers{label=\"$node\"}",
     "legendFormat": "$node tendermint_p2p_peers "
    },
    {}
   ]
  },
  {
   "title": "Total Active Validators",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_validators{label=\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Missing Validator",
   "type": "stat",
   "description": "Validator Num who is missing vote",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_missing_validators{label=\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Total Bonded IP",
   "type": "stat",
   "description": "IP tokens that delegated on active validators",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_validators_power{label=\"$node\"}/100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Block interval in 5 min",
   "type": "timeseries",
   "description": "Average Block interval in recent 5 min",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(cometbft_consensus_block_interval_seconds_sum{label=\"$node\"}[5m])) / sum(rate(cometbft_consensus_block_interval_seconds_count{label=\"$node\"}[5m]))",
     "legendFormat": "Average Block interval in 5 min"
    }
   ]
  },
  {
   "title": "Block Per Minute",
   "type": "timeseries",
   "description": "Block increase per min.",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 7 },
   "targets": [
    {
     "expr": "increase(cometbft_consensus_height{label=\"$node\"}[1m])",
     "legendFormat": "Block Per Minute"
    }
   ]
  },
  {
   "title": "Txs Per Minute",
   "type": "timeseries",
   "description": "Num of txs per minute",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 7 },
   "targets": [
    {
     "expr": "increase(cometbft_consensus_total_txs{label=\"$node\"}[1m])",
     "legendFormat": "Txs Per Minute"
    }
   ]
  },
  {
   "title": "Cosmos tx gas used and wanted",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "cosmos_tx_gas_used{label=\"$node\"}",
     "legendFormat": "tx_gas_used"
    },
    {
     "expr": "cosmos_tx_gas_wanted{label=\"$node\"}",
     "legendFormat": "tx_gas_wanted"
    }
   ]
  },
  {
   "title": "Mempool Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 7 },
   "targets": [
    {
     "expr": "cometbft_mempool_size{label=\"$node\"}",
     "legendFormat": "cometbft_mempool_size"
    }
   ]
  },
  {
   "title": "Block Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "cometbft_consensus_block_size_bytes{label=\"$node\"}",
     "legendFormat": "cometbft consensus block size"
    }
   ]
  },
  { "title": "Validator Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Validator Voting Power",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_validator_power{label=\"$node\"}/1000",
     "legendFormat": "Validator Voting Power"
    }
   ]
  },
  {
   "title": "Validator Last signed block",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 4, "y": 15 },
   "targets": [
    {
     "expr": "cometbft_consensus_validator_last_signed_height{label=\"$node\"}",
     "legendFormat": "Validator last signed block"
    }
   ]
  },
  {
   "title": "Total missed block",
   "type": "timeseries",
   "description": "Validator total missed block",
   "gridPos": { "h": 6, "w": 5, "x": 9, "y": 15 },
   "targets": [
    {
     "expr": "cometbft_consensus_validator_missed_blocks{label=\"$node\"}",
     "legendFormat": "$node total missed block"
    }
   ]
  },
  {
   "title": "Validator Consensus Proposal Created",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 15 },
   "targets": [
    {
     "expr": "cometbft_consensus_proposal_create_count{label=\"$node\"}",
     "legendFormat": "cometbft_consensus_proposal_create_count"
    }
   ]
  },
  {
   "title": "Validator Consensus Proposal Received",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 15 },
   "targets": [
    {
     "expr": "cometbft_consensus_proposal_receive_count{label=\"$node\"}",
     "legendFormat": "cometbft_consensus_proposal_receive_count"
    }
   ]
  },
  { "title": "Geth Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Chain Head Block",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "chain_head_block{label=\"$node\"}",
     "legendFormat": "chain_head_block"
    }
   ]
  },
  {
   "title": "Peers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 3, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "p2p_peers{label=\"$node\"}",
     "legendFormat": "peers"
    },
    {
     "expr": "rate(p2p_dials{label=\"$node\"}[1m])",
     "legendFormat": "dials"
    },
    {
     "expr": "rate(p2p_serves{label=\"$node\"}[1m])",
     "legendFormat": "serves"
    }
   ]
  },
  {
   "title": "Transaction pool",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 9, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "txpool_pending{label=\"$node\"}",
     "legendFormat": "executable"
    },
    {
     "expr": "txpool_queued{label=\"$node\"}",
     "legendFormat": "gapped"
    },
    {
     "expr": "txpool_local{label=\"$node\"}",
     "legendFormat": "local"
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(p2p_ingress{label=\"$node\"}[1m])",
     "legendFormat": "ingress-rate"
    },
    {
     "expr": "rate(p2p_egress{label=\"$node\"}[1m])",
     "legendFormat": "egress-rate"
    },
    {
     "expr": "p2p_ingress{label=\"$node\"}",
     "legendFormat": "igress-flow"
    },
    {
     "expr": "p2p_egress{label=\"$node\"}",
     "legendFormat": "egress-flow"
    }
   ]
  },
  {
   "title": "Block processing",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "chain_execution{label=\"$node\",quantile=\"$quantile\"}",
     "legendFormat": "execution (q=$quantile)"
    },
    {
     "expr": "chain_validation{label=\"$node\", quantile=\"$quantile\"}",
     "legendFormat": "validation (q=$quantile)"
    },
    {
     "expr": "chain_write{label=\"$node\", quantile=\"$quantile\"}",
     "legendFormat": "commit (q=$quantile)"
    },
    {
     "expr": "chain_account_reads{label=\"$node\", quantile=\"$quantile\"}",
     "legendFormat": "account read (q=$quantile)"
    },
    {
     "expr": "chain_account_updates{label=\"$node\", quantile=\"$quantile\"}",
     "legendFormat": "account update (q=$quantile)"
    },
    {
     "expr": "chain_account_hashes{label=\"$node\", quantile=\"$quantile\"}",
     "legendFormat": "account hashe (q=$quantile)"
    },
    {
     "expr": "chain_account_commits{label=\"$node\", quantile=\"$quantile\"}",
     "legendFormat": "account commit (q=$quantile)"
    },
    {
     "expr": "chain_storage_reads{label=\"$node\", quantile=\"$quantile\"}",
     "legendFormat": "storage read (q=$quantile)"
    },
    {
     "expr": "chain_storage_updates{label=\"$node\", quantile=\"$quantile\"}",
     "legendFormat": "storage update (q=$quantile)"
    },
    {
     "expr": "chain_storage_hashes{label=\"$node\", quantile=\"$quantile\"}",
     "legendFormat": "storage hashe (q=$quantile)"
    },
    {
     "expr": "chain_storage_commits{label=\"$node\", quantile=\"$quantile\"}",
     "legendFormat": "storage commit (q=$quantile)"
    },
    {
     "expr": "chain_snapshot_commits{label=\"$node\", quantile=\"$quantile\"}",
     "legendFormat": "snapshot commit (q=$quantile)"
    }
   ]
  },
  {
   "title": "Transaction propagation",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(txpool_valid{label=\"$node\"}[1m])",
     "legendFormat": "valid"
    },
    {
     "expr": "rate(txpool_invalid{label=\"$node\"}[1m])",
     "legendFormat": "invalid"
    },
    {
     "expr": "rate(txpool_underpriced{label=\"$node\"}[1m])",
     "legendFormat": "underpriced"
    },
    {
     "expr": "rate(txpool_pending_discard{label=\"$node\"}[1m])",
     "legendFormat": "executable discard"
    },
    {
     "expr": "rate(txpool_pending_replace{label=\"$node\"}[1m])",
     "legendFormat": "executable replace"
    },
    {
     "expr": "rate(txpool_pending_ratelimit{label=\"$node\"}[1m])",
     "legendFormat": "executable ratelimit"
    },
    {
     "expr": "rate(txpool_pending_nofunds{label=\"$node\"}[1m])",
     "legendFormat": "executable nofunds"
    },
    {
     "expr": "rate(txpool_queued_discard{label=\"$node\"}[1m])",
     "legendFormat": "gapped discard"
    },
    {
     "expr": "rate(txpool_queued_replace{label=\"$node\"}[1m])",
     "legendFormat": "gapped replace"
    },
    {
     "expr": "rate(txpool_queued_ratelimit{label=\"$node\"}[1m])",
     "legendFormat": "gapped ratelimit"
    },
    {
     "expr": "rate(txpool_queued_nofunds{label=\"$node\"}[1m])",
     "legendFormat": "gapped nofunds"
    },
    {
     "expr": "rate(txpool_known{label=\"$node\"}[1m])",
     "legendFormat": "known"
    }
   ]
  },
  { "title": "Server Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "CPU load",
   "type": "gauge",
   "description": "Server CPU load(Percent)",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - avg(irate(node_cpu_seconds_total{label=\"$node\", mode=\"idle\"}[1m])) by (instance)) * 100",
     "legendFormat": "CPU load "
    }
   ]
  },
  {
   "title": "Free memory",
   "type": "timeseries",
   "description": "node_memory_MemFree_bytes+node_memory_Buffers_bytes+node_memory_Cached_bytes+node_memory_Slab_bytes",
   "gridPos": { "h": 8, "w": 5, "x": 4, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes{label=\"$node\"}+node_memory_Buffers_bytes{label=\"$node\"}+node_memory_Cached_bytes{label=\"$node\"}+node_memory_Slab_bytes{label=\"$node\"}",
     "legendFormat": "Free memory"
    }
   ]
  },
  {
   "title": "Free Disk",
   "type": "timeseries",
   "description": "Free Disk on /",
   "gridPos": { "h": 8, "w": 5, "x": 9, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{label=\"$node\",fstype=\"ext4\",mountpoint=\"/\"}",
     "legendFormat": "Free disk on /"
    }
   ]
  },
  {
   "title": "Disk Read and Write",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_bytes_total{label=\"$node\"}[5m])) by (lable)",
     "legendFormat": "Disk(Read)"
    },
    {
     "expr": "sum(rate(node_disk_written_bytes_total{label=\"$node\"}[5m])) by (lable)",
     "legendFormat": "Disk(Write)"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{label=\"$node\", device!=\"lo\"}[5m]))",
     "legendFormat": "inbound traffic"
    },
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{label=\"$node\", device!=\"lo\"}[5m]))",
     "legendFormat": "outbound traffic"
    }
   ]
  }
 ]
}